### ISSUE TITLE
using a  file: url repository throws and error

### ISSUE THREAD

**Issue by cbmarcum** [cbmarcum/skeletal#17]
setup:

1. create a local directory and add a template and manifest.
2. add repository

```
skeletal config add simpleRepositories https://codebuilders.jfrog.io/artifactory/generic/skeletal-templates

skeletal config add simpleRepositories file:///C:/Temp/lazybones-templates
```
list works
```
skeletal list
Available templates in https://codebuilders.jfrog.io/artifactory/generic/skeletal-templates

    lazybones-project
    simple-java-spock-gradle

Available templates in file:///C:/Temp/lazybones-templates

    aoo-client

C:\Temp\skeletal-testing>skeletal create aoo-client my-aoo-client
Creating project from template aoo-client (latest) in 'my-aoo-client'

groovy.lang.MissingMethodException: No signature of method: sun.net.www.protocol.file.FileURLConnection.setFollowRedirects() is applicable for argument types: (Boolean) values: [true]
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:70)
        at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:46)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at java_net_HttpURLConnection$setFollowRedirects.call(Unknown Source)
        at uk.co.cacoethes.lazybones.packagesources.SimplePackageSource.fetchPackageInfo(SimplePackageSource.groovy:105)
        at uk.co.cacoethes.lazybones.packagesources.PackageSource$fetchPackageInfo.call(Unknown Source)
        at uk.co.cacoethes.lazybones.commands.PackageLocationBuilder.getPackageInfo(PackageLocationBuilder.groovy:77)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:194)
        at uk.co.cacoethes.lazybones.commands.PackageLocationBuilder.buildForSimple(PackageLocationBuilder.groovy:65)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:203)
        at uk.co.cacoethes.lazybones.commands.PackageLocationBuilder.buildPackageLocation(PackageLocationBuilder.groovy:26)
        at uk.co.cacoethes.lazybones.commands.PackageLocationBuilder$buildPackageLocation.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:157)
        at uk.co.cacoethes.lazybones.commands.CreateCommand.doExecute(CreateCommand.groovy:85)
        at uk.co.cacoethes.lazybones.commands.AbstractCommand.execute(AbstractCommand.groovy:30)
        at uk.co.cacoethes.lazybones.LazybonesMain.main(LazybonesMain.groovy:89)
```

**Comment by cbmarcum** [comment]
fixed in v0.13.1
